apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "satisfactory.fullname" . }}-env
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
data:
  AUTOPAUSE: "{{ .Values.satisfactoryOpts.autopause | default true }}"
  AUTOSAVEINTERVAL: "{{ .Values.satisfactoryOpts.autosaveInterval | default 300 }}"
  AUTOSAVENUM: "{{ .Values.satisfactoryOpts.autosaveNum | default 3 }}"
  AUTOSAVEONDISCONNECT: "{{ .Values.satisfactoryOpts.autosaveOnDisconnect | default true }}"
  CRASHREPORT: "{{ .Values.satisfactoryOpts.crashReport | default true }}"
  DEBUG: "{{ .Values.satisfactoryOpts.debug | default false }}"
  DISABLESEASONALEVENTS: "{{ .Values.satisfactoryOpts.disableSeasonalEvents | default false }}"
  MAXPLAYERS: "{{ .Values.satisfactoryOpts.maxPlayers | default 4 }}"
  PGID: "{{ .Values.satisfactoryOpts.pgid | default 1000 }}"
  PUID: "{{ .Values.satisfactoryOpts.puid | default 1000 }}"
  SERVERBEACONPORT: "{{ .Values.satisfactoryOpts.serverBeaconPort | default 15000 }}"
  SERVERGAMEPORT: "{{ .Values.satisfactoryOpts.serverGamePort | default 7777 }}"
  SERVERIP: "{{ .Values.satisfactoryOpts.serverIP | default "0.0.0.0" }}"
  SERVERQUERYPORT: "{{ .Values.satisfactoryOpts.serverQueryPort | default 15777 }}"
  SKIPUPDATE: "{{ .Values.satisfactoryOpts.skipUpdate | default false }}"
  STEAMBETA: "{{ .Values.satisfactoryOpts.steamBeta | default false }}"
